create_tmux:
	tmux new -s embedding_lemonde -d 'python embedding_optimized.py'

reattach_tmux:
	tmux attach-session -t embedding_lemonde

kill_session:
	tmux kill-session -t embedding_lemonde

monitor_session:
	tmux ls
# to leave: Press Ctrl + b (release both keys), then press ddb